### ISSUE TITLE
Aggregator halt

### ISSUE THREAD

**Issue by fe3dback** [badoo/liveprof#4]
**Describe the bug**
This command runned from cron script:
```
AGGREGATOR_CONFIG_PATH=/app/docker/php/liveprof.generated.yaml php /app/tools/liveprof-ui/bin/cli.php cron:process-aggregating-jobs
```

and script fail with error
```
Fatal error: Uncaught TypeError: rtrim() expects parameter 1 to be string, null given in /app/tools/liveprof-ui/src/Badoo/LiveProfilerUI/Aggregator.php:268
Stack trace:
#0 /app/tools/liveprof-ui/src/Badoo/LiveProfilerUI/Aggregator.php(268): rtrim(NULL, ',')
#1 /app/tools/liveprof-ui/src/Badoo/LiveProfilerUI/Aggregator.php(250): Badoo\LiveProfilerUI\Aggregator->aggregateRow(Array)
#2 /app/tools/liveprof-ui/src/Badoo/LiveProfilerUI/Aggregator.php(189): Badoo\LiveProfilerUI\Aggregator->aggregate()
#3 /app/tools/liveprof-ui/src/Badoo/LiveProfilerUI/ConsoleCommands/ProcessAggregatingJobsCommand.php(60): Badoo\LiveProfilerUI\Aggregator->process()
#4 /app/tools/liveprof-ui/vendor/symfony/console/Command/Command.php(255): Badoo\LiveProfilerUI\ConsoleCommands\ProcessAggregatingJobsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/tools/liveprof-ui/vendor/symfony/console/Application.php(934): Symfony\Component\Console\Command\Command->run(Object(Symfo in /app/tools/liveprof-ui/src/Badoo/LiveProfilerUI/Aggregator.php on line 268
```

**Expected behavior**
Script is working

**Additional context**
Current state of aggregator_jobs table
```sql
select status, count(*)
from aggregator_jobs
group by status
```

This numbers not changing:
```json
[
  {
    "status": "finished",
    "count(*)": 57
  },
  {
    "status": "new",
    "count(*)": 318
  },
  {
    "status": "processing",
    "count(*)": 19
  }
]
```

**Comment by fe3dback** [comment]
Ups, this issue with liveprof-ui
